


/*
ALTER USER COMPANY DEFAULT ROLE DBA;
select SID from STAFF; where SID = (SYS_CONTEXT('USERENV', 'SESSION_USER' ))
select (SYS_CONTEXT('USERENV', 'ISDBA' )) from dual
SELECT SYS_CONTEXT('SYS_SESSION_ROLES', 'DBA') FROM DUAL;
select SYS_CONTEXT( 'SYS_SESSION_ROLES', 'ALL_ACCOUNTANT' ) from dual
	SELECT * FROM session_roles;
	SELECT * FROM ALL_POLICIES
SELECT * FROM USER_SYS_PRIVS; SELECT * FROM USER_TAB_PRIVS; SELECT * FROM USER_ROLE_PRIVS;
*/