create user hr identified by 123;
grant all_hr to hr with admin option;
create user accountant identified by 123;
grant all_accountant to accountant with admin option;
create user staff1 identified by 123;
grant all_staff to staff1;
create user staff2 identified by 123;
grant all_staff to staff2;
create user applicant identified by 123;
grant all_applicant to applicant;